[project]
name = "manifold_scripts"
version = "0.0.1"
description = "Scripts for analyzing and visualizing manifolds of embeddings of audio clips."
readme = "README.md"
authors = [
    { name = "Aramis Tanelus", email = "aramis.tanelus@nyu.edu" }
]
requires-python = ">=3.12"
dependencies = [
    "audiomanifolds",
    "seaborn>=0.13.2",
    "statsmodels>=0.14.6",
]

[tool.uv.sources]
audiomanifolds = { git = "https://github.com/aramist/audio-embeddings" }
